# Generated by Django 5.0.3 on 2024-05-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=90)),
                ("cpf", models.IntegerField(max_length=14)),
                ("email", models.TextField(max_length=30)),
                ("phone", models.IntegerField(max_length=20)),
                ("address", models.TextField(max_length=255)),
            ],
        ),
    ]
