# Generated by Django 5.0.3 on 2024-05-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0002_user_delete_register"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="senha",
            field=models.CharField(default="valor_padrao", max_length=128),
        ),
    ]
