# Generated by Django 5.0.3 on 2024-05-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0003_user_senha"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="senha",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
    ]
