# Generated by Django 5.0.3 on 2024-05-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_cad_usuarios",
            "0004_rename_senha_user_password_rename_name_user_username_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="password",
            new_name="senha",
        ),
    ]
