# Generated by Django 5.0.3 on 2024-05-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0005_rename_password_user_senha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="senha",
            field=models.CharField(max_length=128),
        ),
    ]
